default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: monumentrove_development

test:
  <<: *default
  database: monumentrove_test

production:
  <<: *default
  database: monumentrove_production
